config/routes.rb
  Rails.application.routes.draw do
    root 'posts#index'
    resources :posts

    resources :sections
    resources :paragraphs
    


  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  ActiveRecord::Base
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord 
    attribute :bodyof , :text
    validates :body, presence: true
    belongs_to :post


 
end 

app/models/posts.rb
# frozen_string_literal: true

class Posts < ApplicationRecord

  attribute :title, :string
  attribute :body ,:text
  attribute :date, :date
  attribute :author, :string


  validates :title, presence: true
  validates :body, presence: true
  validates :date, presence: true
  validates :author, presence: true

  has_many :paragraphs
  
end

app/models/section.rb
class Section < ApplicationRecord
    attribute :title, :string
    validates :title, presence: true
    belongs_to :post
    has_many :paragraphs 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController

end

app/controllers/paragraph_controller.rb
class ParagraphController < ApplicationController
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# frozen_string_literal: true


class PostsController < ApplicationController
def index
    @posts = Posts.all
    render layout: 'application'
  end

  def show
    @post = Posts.find(params[:id])
    @paragraphs = @post.paragraphs
  end


  def create
    @post = Posts.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end




  def new
    # very simple code to create an empty post and send the user
    # to the New view for it (new.html.erb), which will have a
    # form for creating the post
  end





  def edit
    # very simple code to find the post we want and send the
    # user to the Edit view for it (edit.html.erb), which has a
    # form for editing the post
  end

  def first
    @post = Posts.first
  end

  def update

    end

  def destroy
    # very simple code to find the post we're referring to and
    # destroy it.  Once that's done, redirect us to somewhere fun.
  end



  private

  def post_params
    params.require(:post).permit(:title, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paragraph_helper.rb
module ParagraphHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/views/ErrorMessages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error 404</title>

</head>
<body>
<p> unable to render</p>
inde
</body>
</html>

app/views/layouts/application.html.erb
<nav class="navbar navbar-expand-lg bg-secondary border border-light-subtle rounded w-100 p-3 ">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Slice of Tech</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item text-white">
         <%= link_to "Home", posts_path, class: "nav-link active text-white", "aria-current": "page" %>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="https://github.com/lucassimpson0213">Github</a>
        </li>
        <li class="nav-item text-white ">
          <a class="nav-link disabled"></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<body> <%= yield %> </body>

app/views/posts/index.html.erb
  <%= stylesheet_link_tag 'Styles', media: 'all' %>
  <p class="h1 text-center fs-3 --bs-emphasis-color-rgb text-white m-3 "> Most Recent Blog Posts</p>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-sm-3 mt-3">
      <div class="card" style="width: 18rem;">
        <img src="https://th.bing.com/th/id/OIP.AKL8lhKfnPcVSElR1r1lpAHaEK?w=290&h=180&c=7&r=0&o=5&dpr=2&pid=1.7" class="card-img-top img-thumbnail" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= post.body %></p>
          <%= link_to post.title , post_path(post), class: "btn btn-primary", method: :get %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <meta charset="UTF-8">
  <title> <%= @post.title %> </title>
</head>
<body>
 <h1 class="fw-bold text-center text-white"><%= @post.title %></h1>
  <% @paragraphs.each do |paragraph| %>
    <div class="row">
      <div class="col my-3">
        <p class="lead text text-center text-white"><%= paragraph.title %></p>
      </div>
    </div>
  <% end %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/views/sections/paragraph.html.erb
<div class = "header" ><%= @post.sections.each |sections| %></div>
<div class = "body" ><%= sections.paragraphs.body %></div>
<%end%>